### ISSUE TITLE
Package builder  parameter?

### ISSUE THREAD

**Issue by Renari** [hayleox/craftboot#12]
The SKCraft wiki says to make the dist folder you run the following command.

```
java -cp target/SKCraftLauncher.jar com.skcraft.launcher.builder.PackageBuilder --version "1.0" --manifest-dest "dist\manifest.json" --objects-dest "dist\objects" --files "src" --config "modpack.json" --objects-url "objects" --version-file "version.json" --libs-url "http://example.com/libraries"
```

However according to the craftboot wiki this same command should be used except with placing SKCraftLauncher with the craftboot jar. This causes a problem relating the to PackageBuilder method. Do I still need to use the SKCraft source to build the dist folder?

**Comment by kurosnow** [comment]
No, you need to use the CraftBoot source.
