### ISSUE TITLE
Installing to system32 instead of homepath

### ISSUE THREAD

**Issue by stupe** [hayleox/craftboot#5]
As stated in title.

**Comment by hayleox** [comment]
Can you open a command prompt and run this command:

`java -jar /path/to/craftboot.jar -Duser.home=C:\Users\YOURNAMEHERE\`

(and replace "/path/to/craftboot.jar" with the actual path to your CraftBoot jar, and replace YOURNAMEHERE with your Windows username)

**Comment by stupe** [comment]
It says Unknown option: -Duser.home=C:\Users\Ike\

**Comment by hayleox** [comment]
For sake of documentation: This conversation began on Twitter with [this tweet](https://twitter.com/stupefier/status/459491970721665024).

**Comment by hayleox** [comment]
Oh I think it might actually have to be this, mea culpa (edit: yep, confirmed that this should work, sorry):

`java -Duser.home=C:\Users\YOURNAMEHERE\ -jar /path/to/craftboot.jar`

**Comment by stupe** [comment]
This is what I got:

[info] Not bootstrapped
[info] Using current directory C:\Users\Ike.
[info] Cleaning up temporary extracted files directory...
[info] Enumerating instance list...
[info] Available remote instance: 'modpack' at version 1.2
[info] 1 instance(s) enumerated.
[info] Checking for update...

The launcher loaded afterwards.

**Comment by hayleox** [comment]
Oh sorry, could you use the jar for CraftBoot instead of for craftboot-launcher?

Also, once you run it, check to see if C:\Users\Ike\.craftboot\ exists.

**Comment by stupe** [comment]
Ok, I ran it and C:\Users\Ike.craftboot\ does exist now.

**Comment by hayleox** [comment]
Okay, so the issue appears to be that Java does not get the right value for
the "user.home" system property on Windows sometimes (the issue was already
reported on Java's bug report system, but wasn't marked as resolved until
Java 8 was released... ten years after it was reported).

I will switch to a more reliable way to retrieve the home directory, and
release an update for CraftBoot ASAP. (this is a super busy week for me, so
sorry if I can't get it out tonight!)

**Comment by stupe** [comment]
There's no rush. Glad we could get it figured out, I'll keep an eye out for the update. Thanks a bunch for the help!

**Comment by hayleox** [comment]
After much too much delay, CraftBoot v1.0.2 should fix this bug! On Windows, the user home folder is now determined based on the environment variable %USERPROFILE%.
