### ISSUE TITLE
too much ForgeModLoader-client-0.log in instance folder

### ISSUE THREAD

**Issue by smenes** [hayleox/craftboot#6]
hi,
the old ForgeModLoader-client-0.log need to be deleted

now my instance look like that http://pastebin.com/p3985UG9

**Comment by hayleox** [comment]
That looks like an issue with ForgeModLoader rather than with CraftBoot. Perhaps you have some debug option enabled in your FML config? I don't know, I'm not intimately familiar with the workings of FML; you might try asking on the Minecraft Forge forums.

**Comment by hayleox** [comment]
Since this doesn't appear to be a CraftBoot issue, I'm gonna close it, though feel free to reopen it if I'm mistaken.
