### ISSUE TITLE
java flags 

### ISSUE THREAD

**Issue by lynxeffect86** [hayleox/craftboot#8]
The game is running. Please wait.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx1G -XX:PermSize=256m -XX:MaxPermSize=512m
Process ended with code: 1

i get this no matter the flags in the modpack.json i put i need actually 4 gig min to run my mod pack

**Comment by hayleox** [comment]
Instead of putting flags in modpack.json, try setting the memory and PermGen with the Options button in the launcher.

**Comment by lynxeffect86** [comment]
did that and it works thanks

**Comment by hayleox** [comment]
No prob!
